In [3]:
import numpy as np

timesteps = 10
input_features = 4
output_features = 8

inputs = np.random.random((timesteps, input_features))

state_t = np.zeros((output_features, ))

W = np.random.random((output_features, input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features, ))

successive_outputs = []
print('----W------')
print(W)
print('----U----- ')
print(U)
print('----b----- ')
print(b)

for input_t in inputs: 
    print(' -----LOOP 1 ---------- ')
    print('input_t ',  input_t)
    temp = np.dot(W, input_t) + np.dot(U, state_t) + b
    print('before activation ', temp)
    output_t = np.tanh(temp)
    successive_outputs.append(output_t)
    print('output_t ', output_t)
    state_t = output_t

final_output_sequence = np.concatenate(successive_outputs, axis=0)



----W------
[[0.34665608 0.87701553 0.83045774 0.40620043]
 [0.62473047 0.2512939  0.06250751 0.65248872]
 [0.03229742 0.25337133 0.57444043 0.25612979]
 [0.36093917 0.17139363 0.95872037 0.56326524]
 [0.11777015 0.76617368 0.81764926 0.24075157]
 [0.22175523 0.07740718 0.82816023 0.57369792]
 [0.21827598 0.22881769 0.43236675 0.78408871]
 [0.40291564 0.25900895 0.69625559 0.7555642 ]]
----U----- 
[[0.16627564 0.8444867  0.86608699 0.5313811  0.79264423 0.78393934
  0.45118258 0.41317876]
 [0.86786476 0.16004475 0.29487439 0.35936565 0.80657397 0.39700281
  0.96454282 0.29319072]
 [0.56331032 0.29489228 0.27796317 0.8976819  0.80316923 0.41375637
  0.33384251 0.94701294]
 [0.4045307  0.23362455 0.73976937 0.80927237 0.9532345  0.8309665
  0.1936975  0.15492258]
 [0.22667319 0.43113473 0.9443509  0.21502964 0.84212134 0.29852647
  0.2112094  0.5381221 ]
 [0.48257281 0.75158952 0.9746859  0.04943609 0.87871739 0.81447499
  0.43176011 0.6397871 ]
 [0.18487026 0.51723459 0.2184351  0.52464